#!/usr/bin/env bash

wal -i $HOME/Pictures/wallpapers -s
sassc --style expanded "$(dirname "$0")/scss/style.scss" > "$(dirname "$0")/style.css" &&
osascript <<EOD
  tell application "Übersicht"
  	refresh widget id "Pecan-background-coffee"
  end tell
EOD
