#!/usr/bin/env bash

wal -ets -i $HOME/Pictures/wallpapers
sassc --style expanded "$(dirname "$0")/scss/style.scss" > "$(dirname "$0")/style.css" &&
true
#osascript <<EOD
#  tell application "Übersicht"
#  	refresh widget id "Pecan-background-coffee"
#  end tell
#EOD

