#!/bin/bash
# depends on ifstat

/usr/local/bin/ifstat -n -z -i en0 -S 1 1 | awk 'FNR == 3 {print $2}' | awk '{ suffix="KMGT"; for(i=1; $1>1024 && i < length(suffix); i++) $1/=1024; print int($1) substr(suffix, i, 1), $3; }'